Hardware Toolbox: Audio Class Reference
Audio Class Reference
Audio system class.
#include <audio_interface.h>
Public Member Functions
void setLowPassCutoff (float freq)
void setHighPassCutoff (float freq)
void setRmsCutoff (float freq)
int init ()
Initialise interface.
void close ()
Close interface.
void callback (const float *inLR, float *outLR, unsigned long frameCount)
Callback function.
int getData (double *out, int nMax)
Read from interface.
Protected Member Functions
void initProcess ()
Initialise signal processing.
Protected Attributes
TwoPole lp1
TwoPole lp2
TwoPole hp1
TwoPole hp2
TwoPole lpL
TwoPole lpR
TwoPole lpLa
TwoPole lpRa
RingBuffer rb
PaStream * stream
PortAudio stream struct, for streaming data from soundcard.
int framesToGo
float sampleRate
float hpCut
float lpCut
float rmsCut
float outFreqL
float outFreqR
bool inProcess
float ph1
float ph2
CriticalSection critSec
Detailed Description
Audio system class.
Holds the PortAudio stream, and a set of filters/buffers that process the recorded data.
Member Function Documentation
void Audio::callback (const float * inLR, float * outLR, unsigned long frameCount)
Callback function.
This function is passed to the PortAudio stream for processing the signal from the soundcard.
Parameters
[in] inLR
[in] outLR
[in] frameCount
References RingBuffer::add(), CriticalSection::enter(), and CriticalSection::leave().
void Audio::close ()
Close interface.
Stops and closes the PortAudio stream, deallocates resources used by PortAudio, exits.
References stream.
int Audio::getData (double * out, int nMax)
Read from interface.
Parameters
[out] out
[in] nMax
Returns
no. elements read from ring buffer if successful, -1 otherwise.
References AUDIO_TIMEOUT, RingBuffer::clear(), RingBuffer::elements, CriticalSection::enter(), CriticalSection::leave(), RingBuffer::left, RingBuffer::right, and RingBuffer::start.
int Audio::init ()
Initialise interface.
This function
detects audio devices and selects the one with the lowest latency with at least two i/o channels
calls initProcess() to set up filters and buffers
sets up a PortAudio stream to gather data from the device
Returns
1 if successful, 0 otherwise.
no. audio devices available
some 'large' latency value in seconds (used in selecting the best device to use – see below)
index of the best device (used in selecting the best device to use – see below)
PortAudio error codes
struct providing information and capabilities of PortAudio devices
struct containing information about a particular host API
parameters for one direction (input or output) of a stream.
I/O latency (initialise to 'large' latency)
References audioCallback(), initProcess(), and stream.
void Audio::initProcess () protected
Initialise signal processing.
This function sets up a collection of filters and buffers for processing the signal from the soundcard.
References RingBuffer::clear().
Referenced by init().
The documentation for this class was generated from the following files:
/home/fan/hwt/audio/include/audio_interface.h
/home/fan/hwt/audio/src/audio_interface.cpp