Hardware Toolbox: /home/fan/hwt/vsa/src/libedinburghvsa.c File Reference
libedinburghvsa.c File Reference
Edinburgh VSA
Library of functions for calculating dynamics properties of the Edinburgh VSA.
#include <libedinburghvsa.h>
Functions
void cross (double a[3], double b[3], double c[3])
Three dimensional cross product.
void edinburghvsa_model_init (edinburghvsa_model *model)
Initialise model struct (set default parameters).
void edinburghvsa_model_get_acceleration (double *acc, double *x, double *u, edinburghvsa_model *model)
Calculate joint accleration as a function of current state and command.
void edinburghvsa_model_get_torque (double *tau, double *x, double *u, edinburghvsa_model *model)
Calculate total joint torque as a function of current state and command.
void edinburghvsa_model_get_actuator_torque (double *tau, double *x, double *u, edinburghvsa_model *model)
Calculate joint torque due to actuators as a function of current state and command.
void edinburghvsa_model_get_damping_torque (double *tau, double *x, double *u, edinburghvsa_model *model)
Calculate joint torque due to damping as a function of current state and command.
void edinburghvsa_model_get_gravity_torque (double *tau, double *x, double *u, edinburghvsa_model *model)
Calculate joint torque due to gravity as a function of current state and command.
void edinburghvsa_model_get_friction_torque (double *tau, double *x, double *u, edinburghvsa_model *model)
Calculate joint torque due to friction as a function of current state and command.
void edinburghvsa_model_get_stiffness (double *k, double *x, double *u, edinburghvsa_model *model)
Calculate stiffness as a function of current state and command.
void edinburghvsa_model_get_stiffness_jacobian (double *J, double *x, double *u, edinburghvsa_model *model)
Calculate Jacobian of stiffness with respect to motor commands (as a function of current state and command).
void edinburghvsa_model_get_equilibrium_position (double *q0, double *x, double *u, edinburghvsa_model *model)
Calculate equilibrium position as a function of current state and command.
void edinburghvsa_model_get_equilibrium_position_jacobian (double *J, double *x, double *u, edinburghvsa_model *model)
Calculate Jacobian of equilibrium position with respect to motor commands (as a function of current state and command).
void edinburghvsa_model_get_motor_positions (double *m, double *x, edinburghvsa_model *model)
Calculate motor positions based on finite impulse response filters.
Detailed Description
Library of functions for calculating dynamics properties of the Edinburgh VSA.
Author
Matthew Howard (MH), matth.nosp@m.ew.h.nosp@m.oward.nosp@m.@ed..nosp@m.ac.uk
Date
August 2010
See Also
Matlab wrappers to this library
Function Documentation
void cross (double a[3], double b[3], double c[3])
Three dimensional cross product.
Parameters
[out] c cross product
[in] a,b vectors to cross
Referenced by edinburghvsa_model_get_stiffness().
void edinburghvsa_model_get_acceleration (double * acc, double * x, double * u, edinburghvsa_model * model)
Calculate joint accleration as a function of current state and command.
Parameters
[out] acc joint acceleration
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements
References edinburghvsa_model_get_torque(), and edinburghvsa_model::inertia.
Referenced by mexFunction().
void edinburghvsa_model_get_actuator_torque (double * tau, double * x, double * u, edinburghvsa_model * model)
Calculate joint torque due to actuators as a function of current state and command.
Parameters
[out] tau torque
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements
where
are spring forces with ,
are the vectors along the springs ,
are moment arms .
Note
This calculation is based on the derivation given in: Djordje Mitrovic, Stefan Klanke and Sethu Vijayakumar, Learning Impedance Control of Antagonistic Systems based on Stochastic Optimisation Principles, International Journal of Robotic Research, Vol. 30, No. 5, pp. 556-573 (2011).
References edinburghvsa_model::joint_to_motor_axis_x_separation, edinburghvsa_model::joint_to_motor_axis_y_separation, edinburghvsa_model::lever_length, edinburghvsa_model::link_lever_length, edinburghvsa_model::spring_constant, and edinburghvsa_model::spring_rest_length.
Referenced by edinburghvsa_model_get_equilibrium_position(), edinburghvsa_model_get_torque(), and mexFunction().
void edinburghvsa_model_get_damping_torque (double * tau, double * x, double * u, edinburghvsa_model * model)
Calculate joint torque due to damping as a function of current state and command.
Parameters
[out] tau torque
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements
References edinburghvsa_model::damping_constant.
Referenced by edinburghvsa_model_get_torque().
void edinburghvsa_model_get_equilibrium_position (double * q0, double * x, double * u, edinburghvsa_model * model)
Calculate equilibrium position as a function of current state and command.
Parameters
[out] q0 joint equilibrium position
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
Todo:
This uses a line search around the current state. Efficiency could be improved by deriving the roots where tau=0 analytically.
References DIMX, and edinburghvsa_model_get_actuator_torque().
Referenced by edinburghvsa_model_get_equilibrium_position_jacobian(), and mexFunction().
void edinburghvsa_model_get_equilibrium_position_jacobian (double * J, double * x, double * u, edinburghvsa_model * model)
Calculate Jacobian of equilibrium position with respect to motor commands (as a function of current state and command).
Parameters
[out] J joint equilibrium position
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
Note
This calculation is based on finite differences.
References DIMU, and edinburghvsa_model_get_equilibrium_position().
Referenced by mexFunction().
void edinburghvsa_model_get_friction_torque (double * tau, double * x, double * u, edinburghvsa_model * model)
Calculate joint torque due to friction as a function of current state and command.
Parameters
[out] tau torque
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements where and are the viscous and Coulomb friction constants, respectively.
References edinburghvsa_model::coulomb_friction, and edinburghvsa_model::viscous_friction.
Referenced by edinburghvsa_model_get_torque().
void edinburghvsa_model_get_gravity_torque (double * tau, double * x, double * u, edinburghvsa_model * model)
Calculate joint torque due to gravity as a function of current state and command.
Parameters
[out] tau torque
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements
References edinburghvsa_model::gravity_constant.
Referenced by edinburghvsa_model_get_torque().
void edinburghvsa_model_get_motor_positions (double * m, double * x, edinburghvsa_model * model)
Calculate motor positions based on finite impulse response filters.
Parameters
[out] m motor positions
[in] x filter states (velocity, acceleration)
[in] model model struct
Todo:
This function is no longer used and should be removed.
References edinburghvsa_model::b_filter.
Referenced by mexFunction().
void edinburghvsa_model_get_stiffness (double * k, double * x, double * u, edinburghvsa_model * model)
Calculate stiffness as a function of current state and command.
Parameters
[out] k joint stiffness
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements
where is the actuator torque (i.e., torque due to the variable stiffness mechanism).
References cross(), edinburghvsa_model::joint_to_motor_axis_x_separation, edinburghvsa_model::joint_to_motor_axis_y_separation, edinburghvsa_model::lever_length, edinburghvsa_model::link_lever_length, edinburghvsa_model::spring_constant, and edinburghvsa_model::spring_rest_length.
Referenced by edinburghvsa_model_get_stiffness_jacobian(), and mexFunction().
void edinburghvsa_model_get_stiffness_jacobian (double * J, double * x, double * u, edinburghvsa_model * model)
Calculate Jacobian of stiffness with respect to motor commands (as a function of current state and command).
Parameters
[out] J joint stiffness Jacobian
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
Todo:
This calculation is currently based on finite differences. Accuracy and effieciency could be improved by finding the analytic expression for this.
References DIMU, and edinburghvsa_model_get_stiffness().
Referenced by mexFunction().
void edinburghvsa_model_get_torque (double * tau, double * x, double * u, edinburghvsa_model * model)
Calculate total joint torque as a function of current state and command.
Parameters
[out] tau torque
[in] x state (postion, velocity)
[in] u command (motor positions in radiens)
[in] model model struct
This implements
References edinburghvsa_model_get_actuator_torque(), edinburghvsa_model_get_damping_torque(), edinburghvsa_model_get_friction_torque(), and edinburghvsa_model_get_gravity_torque().
Referenced by edinburghvsa_model_get_acceleration().
void edinburghvsa_model_init (edinburghvsa_model * model)
Initialise model struct (set default parameters).
Parameters
model model struct.
References edinburghvsa_model::b_filter, edinburghvsa_model::coulomb_friction, edinburghvsa_model::damping_constant, edinburghvsa_model::gravity_constant, edinburghvsa_model::inertia, edinburghvsa_model::joint_to_motor_axis_x_separation, edinburghvsa_model::joint_to_motor_axis_y_separation, edinburghvsa_model::lever_length, edinburghvsa_model::link_lever_length, edinburghvsa_model::spring_constant, edinburghvsa_model::spring_rest_length, edinburghvsa_model::umax, edinburghvsa_model::umin, and edinburghvsa_model::viscous_friction.
Referenced by mexFunction().