Hardware Toolbox: /home/fan/hwt/vsa/include/libmaccepa.h File Reference
libmaccepa.h File Reference
MACCEPA
Library of functions for calculating dynamics properties of the MACCEPA.
#include <math.h>
#include <stdio.h>
#include <string.h>
#include "../sketchbook/maccepa/defines.h"
Data Structures
struct maccepa_model
struct containing dynamics model parameters.
Macros
#define DIMX 2*DIMQ
State dimensionality.
Functions
void maccepa_model_init (maccepa_model *model)
Initialise model struct (set default parameters).
void maccepa_model_get_torque (double *tau, double *x, double *u, maccepa_model *model)
Calculate total joint torque as a function of current state and command.
void maccepa_model_get_actuator_torque (double *tau, double *x, double *u, maccepa_model *model)
Calculate joint torque due to actuators as a function of current state and command.
void maccepa_model_get_damping_torque (double *tau, double *x, double *u, maccepa_model *model)
Calculate joint torque due to damping as a function of current state and command.
void maccepa_model_get_gravity_torque (double *tau, double *x, double *u, maccepa_model *model)
Calculate joint torque due to gravity as a function of current state and command.
void maccepa_model_get_friction_torque (double *tau, double *x, double *u, maccepa_model *model)
Calculate joint torque due to friction as a function of current state and command.
void maccepa_model_get_acceleration (double *acc, double *x, double *u, maccepa_model *model)
Calculate joint accleration as a function of current state and command.
void maccepa_model_get_equilibrium_position (double *q0, double *x, double *u, maccepa_model *model)
Calculate equilibrium position as a function of current state and command.
void maccepa_model_get_equilibrium_position_jacobian (double *J, double *x, double *u, maccepa_model *model)
Calculate Jacobian of equilibrium position with respect to motor commands (as a function of current state and command).
void maccepa_model_get_stiffness (double *k, double *x, double *u, maccepa_model *model)
Calculate stiffness as a function of current state and command.
void maccepa_model_get_stiffness_jacobian (double *J, double *x, double *u, maccepa_model *model)
Calculate Jacobian of stiffness with respect to motor commands (as a function of current state and command).
void maccepa_model_get_damping (double *b, double *x, double *u, maccepa_model *model)
Calculate damping as a function of current state and command.
void maccepa_model_get_spring_force (double *f, double *x, double *u, maccepa_model *model)
Calculate spring force as a function of current state and command.
void maccepa_model_get_motor_positions (double *m, double *x, maccepa_model *model)
Calculate motor positions based on finite impulse response filters.
Detailed Description
Library of functions for calculating dynamics properties of the MACCEPA.
Function Documentation
void maccepa_model_get_acceleration (double * acc, double * x, double * u, maccepa_model * model)
Calculate joint accleration as a function of current state and command.
Parameters
[out] acc joint acceleration
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements
References maccepa_model::inertia, and maccepa_model_get_torque().
Referenced by mexFunction().
void maccepa_model_get_actuator_torque (double * tau, double * x, double * u, maccepa_model * model)
Calculate joint torque due to actuators as a function of current state and command.
Parameters
[out] tau torque
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements
Note
This calculation is based on the derivation given in: Ham, R. V.; Vanderborght, B.; Damme, M. V.; Verrelst, B. & Lefeber, D. MACCEPA, the mechanically adjustable compliance and controllable equilibrium position actuator: Design and implementation in a biped robot, Robotics and Autonomous Systems, 2007, 55, 761-768
References maccepa_model::drum_radius, maccepa_model::lever_length, maccepa_model::pin_displacement, and maccepa_model::spring_constant.
Referenced by maccepa_model_get_torque(), and mexFunction().
void maccepa_model_get_damping (double * b, double * x, double * u, maccepa_model * model)
Calculate damping as a function of current state and command.
Parameters
[out] b joint damping
[in] x state (position, velocity)
[in] u command (motor positions (rad), damping command (duty cycle))
[in] model model struct
Note
This is a place holder for a damping model!
Todo:
Integrate model of damper motor here.
References maccepa_model::damping_constant.
Referenced by maccepa_model_get_damping_torque().
void maccepa_model_get_damping_torque (double * tau, double * x, double * u, maccepa_model * model)
Calculate joint torque due to damping as a function of current state and command.
Parameters
[out] tau torque
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements
Note
Currently, if VARIABLE_DAMPING is defined, this returns zero torque. Temporarily, the damping modelling is being done on the Matlab side until we get a good damping model (or until we know the right model to use).
References maccepa_model_get_damping().
Referenced by maccepa_model_get_torque().
void maccepa_model_get_equilibrium_position (double * q0, double * x, double * u, maccepa_model * model)
Calculate equilibrium position as a function of current state and command.
Parameters
[out] q0 joint equilibrium position
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements
Referenced by mexFunction().
void maccepa_model_get_equilibrium_position_jacobian (double * J, double * x, double * u, maccepa_model * model)
Calculate Jacobian of equilibrium position with respect to motor commands (as a function of current state and command).
Parameters
[out] J joint equilibrium position
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements
Referenced by mexFunction().
void maccepa_model_get_friction_torque (double * tau, double * x, double * u, maccepa_model * model)
Calculate joint torque due to friction as a function of current state and command.
Parameters
[out] tau torque
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements where and are the viscous and Coulomb friction constants, respectively.
References maccepa_model::coulomb_friction, and maccepa_model::viscous_friction.
Referenced by maccepa_model_get_torque().
void maccepa_model_get_gravity_torque (double * tau, double * x, double * u, maccepa_model * model)
Calculate joint torque due to gravity as a function of current state and command.
Parameters
[out] tau torque
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements
References maccepa_model::gravity_constant.
Referenced by maccepa_model_get_torque().
void maccepa_model_get_motor_positions (double * m, double * x, maccepa_model * model)
Calculate motor positions based on finite impulse response filters.
Parameters
[out] m motor positions
[in] x filter states (velocity, acceleration)
[in] model model struct
Todo:
This function is no longer used and should be removed.
References maccepa_model::b_filter.
Referenced by mexFunction().
void maccepa_model_get_spring_force (double * f, double * x, double * u, maccepa_model * model)
Calculate spring force as a function of current state and command.
Parameters
[out] force spring force
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements where is the spring extension.
References maccepa_model::drum_radius, maccepa_model::lever_length, maccepa_model::pin_displacement, and maccepa_model::spring_constant.
Referenced by mexFunction().
void maccepa_model_get_stiffness (double * k, double * x, double * u, maccepa_model * model)
Calculate stiffness as a function of current state and command.
Parameters
[out] k joint stiffness
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements
where is the actuator torque (i.e., torque due to the variable stiffness mechanism).
References maccepa_model::drum_radius, maccepa_model::lever_length, maccepa_model::pin_displacement, and maccepa_model::spring_constant.
Referenced by maccepa_model_get_stiffness_jacobian(), and mexFunction().
void maccepa_model_get_stiffness_jacobian (double * J, double * x, double * u, maccepa_model * model)
Calculate Jacobian of stiffness with respect to motor commands (as a function of current state and command).
Parameters
[out] J joint stiffness Jacobian
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
Todo:
This calculation is currently based on finite differences. Accuracy and effieciency could be improved by finding the analytic expression for this.
References DIMU, and maccepa_model_get_stiffness().
Referenced by mexFunction().
void maccepa_model_get_torque (double * tau, double * x, double * u, maccepa_model * model)
Calculate total joint torque as a function of current state and command.
Parameters
[out] tau torque
[in] x state (velocity, acceleration)
[in] u command (motor positions in radiens)
[in] model model struct
This implements
References maccepa_model_get_actuator_torque(), maccepa_model_get_damping_torque(), maccepa_model_get_friction_torque(), and maccepa_model_get_gravity_torque().
Referenced by maccepa_model_get_acceleration().
void maccepa_model_init (maccepa_model * model)
Initialise model struct (set default parameters).
Parameters
model model struct.
References maccepa_model::b_filter, maccepa_model::coulomb_friction, maccepa_model::damping_constant, maccepa_model::drum_radius, maccepa_model::gravity_constant, maccepa_model::inertia, maccepa_model::lever_length, maccepa_model::link_length, maccepa_model::pin_displacement, maccepa_model::spring_constant, maccepa_model::umax, maccepa_model::umin, and maccepa_model::viscous_friction.
Referenced by mexFunction().