Hardware Toolbox: /home/fan/hwt/vsa/src/mex_libedinburghvsa.c File Reference
mex_libedinburghvsa.c File Reference
Edinburgh VSA
MEX gateway to Edinburgh VSA dynamics library (libedinburghvsa).
#include <mex.h>
#include <matrix.h>
#include <libedinburghvsa.h>
Functions
void mex_libedinburghvsa_model_matlab_to_c (edinburghvsa_model *model, const mxArray *matlab_model)
Converts Matlab model struct into C model struct.
void mex_libedinburghvsa_model_c_to_matlab (mxArray *matlab_model, const edinburghvsa_model *model)
Converts C model struct into Matlab model struct.
bool mex_libedinburghvsa_check_arguments (int nrhs, const mxArray *prhs[])
Check that the arguments passed are correct. (In general the convention is y = f(x,u,model).)
void mexFunction (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
Mex gateway function. Provides access to C functions.
Variables
edinburghvsa_model model
struct containing model parameters.
static char usage_msg []
Mex interface usage message.
Detailed Description
MEX gateway to Edinburgh VSA dynamics library (libedinburghvsa).
Author
Matthew Howard (MH), matth.nosp@m.ew.h.nosp@m.oward.nosp@m.@ed..nosp@m.ac.uk
Date
August 2010
Function Documentation
bool mex_libedinburghvsa_check_arguments (int nrhs, const mxArray * prhs[])
Check that the arguments passed are correct. (In general the convention is y = f(x,u,model).)
Parameters
[in] nrhs number of arguments
[in] prhs argument pointers
Returns
true if arguments are ok, false if not.
References DIMU, and DIMX.
Referenced by mexFunction().
void mex_libedinburghvsa_model_c_to_matlab (mxArray * matlab_model, const edinburghvsa_model * model)
Converts C model struct into Matlab model struct.
Parameters
[out] matlab_model Matlab model struct
[in] model C model struct
References edinburghvsa_model::coulomb_friction, DIMQ, DIMU, edinburghvsa_model::inertia, edinburghvsa_model::joint_to_motor_axis_x_separation, edinburghvsa_model::joint_to_motor_axis_y_separation, edinburghvsa_model::lever_length, edinburghvsa_model::link_lever_length, edinburghvsa_model::spring_constant, edinburghvsa_model::spring_rest_length, edinburghvsa_model::umax, edinburghvsa_model::umin, and edinburghvsa_model::viscous_friction.
Referenced by mexFunction().
void mex_libedinburghvsa_model_matlab_to_c (edinburghvsa_model * model, const mxArray * matlab_model)
Converts Matlab model struct into C model struct.
Parameters
[out] model C model struct
[in] matlab_model Matlab model struct
References edinburghvsa_model::coulomb_friction, DIMU, edinburghvsa_model::inertia, edinburghvsa_model::joint_to_motor_axis_x_separation, edinburghvsa_model::joint_to_motor_axis_y_separation, edinburghvsa_model::lever_length, edinburghvsa_model::link_lever_length, edinburghvsa_model::spring_constant, edinburghvsa_model::spring_rest_length, edinburghvsa_model::umax, edinburghvsa_model::umin, and edinburghvsa_model::viscous_friction.
Referenced by mexFunction().
Variable Documentation
char usage_msg[] static
Initial value:
=
"Usage of Edinburgh VSA model MEX interface:\n"
                "  model_edinburghvsa('function',args) calls function 'function' with arguments args.\n See documentation for which functions are defined.\n"
Mex interface usage message.
Referenced by mexFunction().