Hardware Toolbox: /home/fan/hwt/vsa/src/mex_libmaccepa.c File Reference
mex_libmaccepa.c File Reference
MACCEPA
MEX gateway to MACCEPA dynamics library (libmaccepa).
#include <mex.h>
#include <matrix.h>
#include <libmaccepa.h>
Functions
void mex_libmaccepa_model_matlab_to_c (maccepa_model *model, const mxArray *matlab_model)
Converts Matlab model struct into C model struct.
void mex_libmaccepa_model_c_to_matlab (mxArray *matlab_model, const maccepa_model *model)
Converts C model struct into Matlab model struct.
bool mex_libmaccepa_check_arguments (int nrhs, const mxArray *prhs[])
Check that the arguments passed are correct. (In general the convention is y = f(x,u,model).)
void mexFunction (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
Mex gateway function. Provides access to C functions.
Variables
maccepa_model model
struct containing model parameters.
static char usage_msg []
Mex interface usage message.
Detailed Description
MEX gateway to MACCEPA dynamics library (libmaccepa).
Author
Matthew Howard (MH), matth.nosp@m.ew.h.nosp@m.oward.nosp@m.@ed..nosp@m.ac.uk
Date
August 2010
Function Documentation
bool mex_libmaccepa_check_arguments (int nrhs, const mxArray * prhs[])
Check that the arguments passed are correct. (In general the convention is y = f(x,u,model).)
Parameters
[in] nrhs number of arguments
[in] prhs argument pointers
Returns
true if arguments are ok, false if not.
References DIMU, and DIMX.
Referenced by mexFunction().
void mex_libmaccepa_model_c_to_matlab (mxArray * matlab_model, const maccepa_model * model)
Converts C model struct into Matlab model struct.
Parameters
[out] matlab_model Matlab model struct
[in] model C model struct
References maccepa_model::coulomb_friction, maccepa_model::damping_constant, DIMQ, DIMU, maccepa_model::drum_radius, maccepa_model::gravity_constant, maccepa_model::inertia, maccepa_model::lever_length, maccepa_model::link_length, maccepa_model::pin_displacement, maccepa_model::spring_constant, maccepa_model::umax, maccepa_model::umin, and maccepa_model::viscous_friction.
Referenced by mexFunction().
void mex_libmaccepa_model_matlab_to_c (maccepa_model * model, const mxArray * matlab_model)
Converts Matlab model struct into C model struct.
Parameters
[out] model C model struct
[in] matlab_model Matlab model struct
References maccepa_model::coulomb_friction, maccepa_model::damping_constant, DIMU, maccepa_model::drum_radius, maccepa_model::gravity_constant, maccepa_model::inertia, maccepa_model::lever_length, maccepa_model::link_length, maccepa_model::pin_displacement, maccepa_model::spring_constant, maccepa_model::umax, maccepa_model::umin, and maccepa_model::viscous_friction.
Referenced by mexFunction().
Variable Documentation
char usage_msg[] static
Initial value:
=
"Usage of MACCEPA model MEX interface:\n"
"  model_maccepa('function',args) calls function 'function' with arguments args.\n See documentation for which functions are defined.\n"
Mex interface usage message.
Referenced by mexFunction().