Hardware Toolbox: /home/fan/hwt/serial/include/serial.h File Reference
serial.h File Reference
Simple serial port library for Windows and Linux, written in plain C.
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <termios.h>
#include <unistd.h>
Data Structures
struct SerialPort
Functions
int serialOpenByNumber (SerialPort *SP, int port)
int serialOpenByName (SerialPort *SP, const char *name)
Open serial port by name.
int serialClose (SerialPort *SP)
int serialWrite (SerialPort *SP, int size, void *buffer)
Write to serial port.
int serialRead (SerialPort *SP, int size, void *buffer)
Read from serial port.
int serialSetParameters (SerialPort *SP, int baudrate, int bits, int parity, int stops, int timeout)
Set serial port parameters.
void serialFlushInput (SerialPort *SP)
void serialFlushOutput (SerialPort *SP)
Detailed Description
Simple serial port library for Windows and Linux, written in plain C.
(C) 2008 Stefan Klanke
Function Documentation
int serialOpenByName (SerialPort * SP, const char * name)
Open serial port by name.
Parameters
[out] SP Serial port struct.
[in] name Name of serial port device (e.g. /dev/ttyUSB0).
Returns
1 if opening is successful, 0 otherwise.
Referenced by vsa_arduino_interface_init().
int serialRead (SerialPort * SP, int size, void * buffer)
Read from serial port.
Parameters
[in] SP Serial port struct.
[in] size Size of buffer (?).
[out] buffer Pointer to data buffer.
Returns
1 if read is successful, 0 otherwise.
Referenced by threadFunc().
int serialSetParameters (SerialPort * SP, int baudrate, int bits, int parity, int stops, int timeout)
Set serial port parameters.
Parameters
[in] SP Serial port struct.
[in] baudrate Baudrate.
[in] bits No. data bits.
[in] parity Parity (0 or 1).
[in] stops No. stop bits (1 or 2).
[in] timeout Timeout (in units of 0.1 sec).
Returns
1 if setting is successful, 0 otherwise.
Referenced by vsa_arduino_interface_init().
int serialWrite (SerialPort * SP, int size, void * buffer)
Write to serial port.
Parameters
[in] SP Serial port struct.
[in] size Size of buffer (?).
[in] buffer Pointer to data buffer.
Returns
1 if write is successful, 0 otherwise.
Referenced by threadFunc(), vsa_arduino_interface_write(), and vsa_arduino_interface_write_usec().