Hardware Toolbox: /home/fan/hwt/vsa/src/vsa_arduino_interface.c File Reference
vsa_arduino_interface.c File Reference
Module for interfacing to variable stiffness actuators (e.g., Edinburgh VSA, MACCEPA).
#include <vsa_arduino_interface.h>
Functions
static void * threadFunc (void *data)
I/O thread function. Continually runs in the background, reading from the serial. If new data arrives at the serial it is decoded and written to the measured_state variable.
int vsa_arduino_interface_init (ArduinoInterface *AI, char *device)
Open serial connection with Arduino board, start i/o thread in the background.
int vsa_arduino_interface_check (ArduinoInterface *AI)
Check that Arduino connection has been set up.
void vsa_arduino_interface_close (ArduinoInterface *AI)
Close serial connection with Arduino board, stop background i/o thread.
void vsa_arduino_interface_run_step (ArduinoInterface *AI, double *u, double *y)
Read sensors from the arm, and command new motor positions.
void vsa_arduino_interface_read (ArduinoInterface *AI, double *y)
Read sensors. Values returned will be converted into appropriate units (e.g., angles in radiens, power in W, etc.).
void vsa_arduino_interface_write (ArduinoInterface *AI, double *u)
Command new motor positions u.
void vsa_arduino_interface_write_usec (ArduinoInterface *AI, int *u)
Command new motor positions u.
void vsa_arduino_interface_read_adc (ArduinoInterface *AI, int *y)
Read sensors. Values returned will be as steps of the ADCs.
Detailed Description
Module for interfacing to variable stiffness actuators (e.g., Edinburgh VSA, MACCEPA).
Author
Matthew Howard (MH), matth.nosp@m.ew.h.nosp@m.oward.nosp@m.@ed..nosp@m.ac.uk
Function Documentation
static void* threadFunc (void * data) static
I/O thread function. Continually runs in the background, reading from the serial. If new data arrives at the serial it is decoded and written to the measured_state variable.
Variable for temporary storage of incoming serial data.
Variable for keeping track of the stage of parsing of incoming serial data.
Variable for keeping track of which sensor we are reading from.
Variable for temporary storage of sensor readings during parsing.
Time stamp of data.
References AI, serialRead(), and serialWrite().
Referenced by vsa_arduino_interface_init().
int vsa_arduino_interface_check (ArduinoInterface * AI)
Check that Arduino connection has been set up.
Parameters
AI arduino interface.
References ArduinoInterface::connection_state.
void vsa_arduino_interface_close (ArduinoInterface * AI)
Close serial connection with Arduino board, stop background i/o thread.
Close serial connection with Arduino board, shutdown background i/o thread.
References ArduinoInterface::connection_state, ArduinoInterface::port, ArduinoInterface::thread, ArduinoInterface::thread_state, and ArduinoInterface::threadLock.
int vsa_arduino_interface_init (ArduinoInterface * AI, char * device)
Open serial connection with Arduino board, start i/o thread in the background.
Initialise serial connection with Arduino board, start i/o thread in the background.
Parameters
[in] device Name of serial port to which Arduino is connected.
References ArduinoInterface::command_buffer, ArduinoInterface::connection_state, ArduinoInterface::port, serialOpenByName(), serialSetParameters(), ArduinoInterface::thread, threadFunc(), and ArduinoInterface::threadLock.
void vsa_arduino_interface_read (ArduinoInterface * AI, double * y)
Read sensors. Values returned will be converted into appropriate units (e.g., angles in radiens, power in W, etc.).
Parameters
AI arduino interface.
[out] y double array, containing sensor readings.
Note
Calling this function will block until the next frame of data has arrived from the Arduino.
References ArduinoInterface::measured_state, and ArduinoInterface::timestamp.
void vsa_arduino_interface_read_adc (ArduinoInterface * AI, int * y)
Read sensors. Values returned will be as steps of the ADCs.
Parameters
AI arduino interface.
[out] y double array, containing sensor readings.
Note
Calling this function will block until the next frame of data has arrived from the Arduino.
References ArduinoInterface::measured_state.
void vsa_arduino_interface_run_step (ArduinoInterface * AI, double * u, double * y)
Read sensors from the arm, and command new motor positions.
Parameters
AI arduino interface.
[in] u desired motor positions (rad).
[out] y sensor readings (same units as read).
References ArduinoInterface::command_buffer, ArduinoInterface::measured_state, and ArduinoInterface::timestamp.
void vsa_arduino_interface_write (ArduinoInterface * AI, double * u)
Command new motor positions u.
Parameters
AI arduino interface.
[in] u[DIMU] array of desired motor positions (rad).
Commands are clipped to within U_LLIM_RAD_SERVOx < u[x] < U_ULIM_RAD_SERVOx, and converted to units of .5 usec, before being sent to the Arduino.
Note
This function will NOT block, and there is no guarantee about when the new positions will be sent to the servos.
References ArduinoInterface::command_buffer, ArduinoInterface::port, and serialWrite().
void vsa_arduino_interface_write_usec (ArduinoInterface * AI, int * u)
Command new motor positions u.
Parameters
AI arduino interface.
[in] u[DIMU] array of desired motor positions (.5 usec).
Commands are sent directly to the Arduino. This command mode is meant only for configuring the servos. NO SAFETY LIMITS ARE APPLIED!
Note
This function will NOT block, and there is no guarantee about when the new positions will be sent to the servos.
References ArduinoInterface::command_buffer, DIMU, ArduinoInterface::port, and serialWrite().